TrajectoryPlannerROS:
  max_vel_x: 0.7
  min_vel_x: 0.3
  max_vel_theta: 2.8
  sim_vel: 2.0
  min_in_place_vel_theta: 0.0
  sim_time: 2.0
  sim_granularity: 0.025
  vx_samples: 10
  vtheta_samples: 20

  acc_lim_theta: 2.3
  acc_lim_x: 1.3
  acc_lim_y: 0.0

  holonomic_robot: false    
  meter_scoring: true
  pdist_scale: 4.0    
  gdist_scale: 0.5    
  occdist_scale: 0.02  