# 机器人形状
footprint: [[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]

# 障碍物层参数 (对应 plugins 里的 name: obstacle_layer)
obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  inflation_radius: 0.5
  track_unknown_space: false
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# 膨胀层参数 (对应 plugins 里的 name: inflation_layer)
inflation_layer:
  enabled: true
  cost_scaling_factor: 3.0  # 越大越陡，障碍物周围的危险区越小
  inflation_radius: 0.4