# 机器人形状 (根据 racecar 模型估算，长方形)
footprint: [[0.25, 0.15], [0.25, -0.15], [-0.25, -0.15], [-0.25, 0.15]]
# 如果想要简单的圆形碰撞检测，可以用 robot_radius: 0.25 代替 footprint

obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.5
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}