global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 1.0
  
  # 必须使用静态地图
  static_map: true
  rolling_window: false
  
  # 请删除 origin_x, origin_y, width, height 这些参数（如果有的话）
  # 因为 static_map: true 时，尺寸由上面的 yaml 文件决定

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}