global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  static_map: true       # 关键：不使用静态地图
  rolling_window: false    # 关键：地图跟随机器人移动
  
  
  # 明确指定插件，修复警告
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}